debian/tmp-libc/usr/bin/gencat usr/bin
debian/tmp-libc/usr/bin/getconf usr/bin
debian/tmp-libc/usr/bin/mtrace usr/bin
debian/tmp-libc/usr/bin/rpcgen usr/bin

debian/tmp-libc/usr/lib/*.a usr/lib
debian/tmp-libc/usr/lib/*.o usr/lib
debian/tmp-libc/usr/lib/*.so usr/lib
debian/tmp-libc/usr/include/* usr/include

linux-kernel-headers/include/asm* usr/include
linux-kernel-headers/include/linux usr/include

